-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GrayArray2AXIS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    axis_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    axis_out_TVALID : OUT STD_LOGIC;
    axis_out_TREADY : IN STD_LOGIC;
    axis_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    fifo7_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    fifo7_empty_n : IN STD_LOGIC;
    fifo7_read : OUT STD_LOGIC );
end;


architecture behav of GrayArray2AXIS is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_438 : STD_LOGIC_VECTOR (10 downto 0) := "10000111000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_437 : STD_LOGIC_VECTOR (10 downto 0) := "10000110111";
    constant ap_const_lv11_780 : STD_LOGIC_VECTOR (10 downto 0) := "11110000000";
    constant ap_const_lv11_77F : STD_LOGIC_VECTOR (10 downto 0) := "11101111111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal axis_dst_data_V_1_data_out : STD_LOGIC_VECTOR (23 downto 0);
    signal axis_dst_data_V_1_vld_in : STD_LOGIC;
    signal axis_dst_data_V_1_vld_out : STD_LOGIC;
    signal axis_dst_data_V_1_ack_in : STD_LOGIC;
    signal axis_dst_data_V_1_ack_out : STD_LOGIC;
    signal axis_dst_data_V_1_payload_A : STD_LOGIC_VECTOR (23 downto 0);
    signal axis_dst_data_V_1_payload_B : STD_LOGIC_VECTOR (23 downto 0);
    signal axis_dst_data_V_1_sel_rd : STD_LOGIC := '0';
    signal axis_dst_data_V_1_sel_wr : STD_LOGIC := '0';
    signal axis_dst_data_V_1_sel : STD_LOGIC;
    signal axis_dst_data_V_1_load_A : STD_LOGIC;
    signal axis_dst_data_V_1_load_B : STD_LOGIC;
    signal axis_dst_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal axis_dst_data_V_1_state_cmp_full : STD_LOGIC;
    signal axis_dst_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal axis_dst_last_V_1_vld_in : STD_LOGIC;
    signal axis_dst_last_V_1_vld_out : STD_LOGIC;
    signal axis_dst_last_V_1_ack_in : STD_LOGIC;
    signal axis_dst_last_V_1_ack_out : STD_LOGIC;
    signal axis_dst_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal axis_dst_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal axis_dst_last_V_1_sel_rd : STD_LOGIC := '0';
    signal axis_dst_last_V_1_sel_wr : STD_LOGIC := '0';
    signal axis_dst_last_V_1_sel : STD_LOGIC;
    signal axis_dst_last_V_1_load_A : STD_LOGIC;
    signal axis_dst_last_V_1_load_B : STD_LOGIC;
    signal axis_dst_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal axis_dst_last_V_1_state_cmp_full : STD_LOGIC;
    signal axis_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln119_reg_172 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln119_reg_172_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal fifo7_blk_n : STD_LOGIC;
    signal xi_0_i_reg_95 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln118_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2 : BOOLEAN;
    signal yi_fu_112_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal yi_reg_162 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln125_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_reg_167 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln119_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal xi_fu_130_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal and_ln125_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln125_reg_181 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln_i_fu_147_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal yi_0_i_reg_84 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln125_1_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (icmp_ln118_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (icmp_ln118_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (icmp_ln118_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axis_dst_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                axis_dst_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((axis_dst_data_V_1_ack_out = ap_const_logic_1) and (axis_dst_data_V_1_vld_out = ap_const_logic_1))) then 
                                        axis_dst_data_V_1_sel_rd <= not(axis_dst_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    axis_dst_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                axis_dst_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((axis_dst_data_V_1_ack_in = ap_const_logic_1) and (axis_dst_data_V_1_vld_in = ap_const_logic_1))) then 
                                        axis_dst_data_V_1_sel_wr <= not(axis_dst_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    axis_dst_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                axis_dst_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((axis_dst_data_V_1_state = ap_const_lv2_2) and (axis_dst_data_V_1_vld_in = ap_const_logic_0)) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_dst_data_V_1_vld_in = ap_const_logic_0) and (axis_dst_data_V_1_ack_out = ap_const_logic_1)))) then 
                    axis_dst_data_V_1_state <= ap_const_lv2_2;
                elsif ((((axis_dst_data_V_1_state = ap_const_lv2_1) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0) and (axis_dst_data_V_1_vld_in = ap_const_logic_1)))) then 
                    axis_dst_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((axis_dst_data_V_1_vld_in = ap_const_logic_0) and (axis_dst_data_V_1_ack_out = ap_const_logic_1))) and not(((axis_out_TREADY = ap_const_logic_0) and (axis_dst_data_V_1_vld_in = ap_const_logic_1))) and (axis_dst_data_V_1_state = ap_const_lv2_3)) or ((axis_dst_data_V_1_state = ap_const_lv2_1) and (axis_dst_data_V_1_ack_out = ap_const_logic_1)) or ((axis_dst_data_V_1_state = ap_const_lv2_2) and (axis_dst_data_V_1_vld_in = ap_const_logic_1)))) then 
                    axis_dst_data_V_1_state <= ap_const_lv2_3;
                else 
                    axis_dst_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    axis_dst_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                axis_dst_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((axis_dst_last_V_1_vld_out = ap_const_logic_1) and (axis_dst_last_V_1_ack_out = ap_const_logic_1))) then 
                                        axis_dst_last_V_1_sel_rd <= not(axis_dst_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    axis_dst_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                axis_dst_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((axis_dst_last_V_1_ack_in = ap_const_logic_1) and (axis_dst_last_V_1_vld_in = ap_const_logic_1))) then 
                                        axis_dst_last_V_1_sel_wr <= not(axis_dst_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    axis_dst_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                axis_dst_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((axis_dst_last_V_1_state = ap_const_lv2_2) and (axis_dst_last_V_1_vld_in = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_dst_last_V_1_vld_in = ap_const_logic_0) and (axis_dst_last_V_1_ack_out = ap_const_logic_1)))) then 
                    axis_dst_last_V_1_state <= ap_const_lv2_2;
                elsif ((((axis_dst_last_V_1_state = ap_const_lv2_1) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0) and (axis_dst_last_V_1_vld_in = ap_const_logic_1)))) then 
                    axis_dst_last_V_1_state <= ap_const_lv2_1;
                elsif (((not(((axis_dst_last_V_1_vld_in = ap_const_logic_0) and (axis_dst_last_V_1_ack_out = ap_const_logic_1))) and not(((axis_out_TREADY = ap_const_logic_0) and (axis_dst_last_V_1_vld_in = ap_const_logic_1))) and (axis_dst_last_V_1_state = ap_const_lv2_3)) or ((axis_dst_last_V_1_state = ap_const_lv2_1) and (axis_dst_last_V_1_ack_out = ap_const_logic_1)) or ((axis_dst_last_V_1_state = ap_const_lv2_2) and (axis_dst_last_V_1_vld_in = ap_const_logic_1)))) then 
                    axis_dst_last_V_1_state <= ap_const_lv2_3;
                else 
                    axis_dst_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    xi_0_i_reg_95_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (icmp_ln118_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                xi_0_i_reg_95 <= ap_const_lv11_0;
            elsif (((icmp_ln119_fu_124_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                xi_0_i_reg_95 <= xi_fu_130_p2;
            end if; 
        end if;
    end process;

    yi_0_i_reg_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                yi_0_i_reg_84 <= yi_reg_162;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                yi_0_i_reg_84 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln119_fu_124_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln125_reg_181 <= and_ln125_fu_142_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((axis_dst_data_V_1_load_A = ap_const_logic_1)) then
                axis_dst_data_V_1_payload_A <= or_ln_i_fu_147_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((axis_dst_data_V_1_load_B = ap_const_logic_1)) then
                axis_dst_data_V_1_payload_B <= or_ln_i_fu_147_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((axis_dst_last_V_1_load_A = ap_const_logic_1)) then
                axis_dst_last_V_1_payload_A <= and_ln125_reg_181;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((axis_dst_last_V_1_load_B = ap_const_logic_1)) then
                axis_dst_last_V_1_payload_B <= and_ln125_reg_181;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln119_reg_172 <= icmp_ln119_fu_124_p2;
                icmp_ln119_reg_172_pp0_iter1_reg <= icmp_ln119_reg_172;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (icmp_ln118_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln125_reg_167 <= icmp_ln125_fu_118_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                yi_reg_162 <= yi_fu_112_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, axis_out_TREADY, axis_dst_data_V_1_state, axis_dst_last_V_1_state, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln118_fu_106_p2, ap_CS_fsm_state2, icmp_ln119_fu_124_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (icmp_ln118_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (icmp_ln118_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln119_fu_124_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((icmp_ln119_fu_124_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    and_ln125_fu_142_p2 <= (icmp_ln125_reg_167 and icmp_ln125_1_fu_136_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state6 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(fifo7_empty_n, ap_enable_reg_pp0_iter1, icmp_ln119_reg_172)
    begin
                ap_block_pp0_stage0_01001 <= ((icmp_ln119_reg_172 = ap_const_lv1_0) and (fifo7_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(fifo7_empty_n, ap_enable_reg_pp0_iter1, icmp_ln119_reg_172, ap_enable_reg_pp0_iter2, ap_block_state4_io, ap_block_state5_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state5_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or ((icmp_ln119_reg_172 = ap_const_lv1_0) and (fifo7_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(fifo7_empty_n, ap_enable_reg_pp0_iter1, icmp_ln119_reg_172, ap_enable_reg_pp0_iter2, ap_block_state4_io, ap_block_state5_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state5_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or ((icmp_ln119_reg_172 = ap_const_lv1_0) and (fifo7_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(axis_out_TREADY, axis_dst_data_V_1_state, axis_dst_last_V_1_state)
    begin
                ap_block_state2 <= ((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_io_assign_proc : process(axis_dst_data_V_1_ack_in, icmp_ln119_reg_172)
    begin
                ap_block_state4_io <= ((icmp_ln119_reg_172 = ap_const_lv1_0) and (axis_dst_data_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter1_assign_proc : process(fifo7_empty_n, icmp_ln119_reg_172)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((icmp_ln119_reg_172 = ap_const_lv1_0) and (fifo7_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_io_assign_proc : process(axis_dst_data_V_1_ack_in, icmp_ln119_reg_172_pp0_iter1_reg)
    begin
                ap_block_state5_io <= ((icmp_ln119_reg_172_pp0_iter1_reg = ap_const_lv1_0) and (axis_dst_data_V_1_ack_in = ap_const_logic_0));
    end process;

        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln119_fu_124_p2)
    begin
        if ((icmp_ln119_fu_124_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, axis_out_TREADY, axis_dst_data_V_1_state, axis_dst_last_V_1_state, icmp_ln118_fu_106_p2, ap_CS_fsm_state2)
    begin
        if ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (icmp_ln118_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(axis_out_TREADY, axis_dst_data_V_1_state, axis_dst_last_V_1_state, icmp_ln118_fu_106_p2, ap_CS_fsm_state2)
    begin
        if ((not(((axis_dst_last_V_1_state = ap_const_lv2_1) or (axis_dst_data_V_1_state = ap_const_lv2_1) or ((axis_dst_data_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)) or ((axis_dst_last_V_1_state = ap_const_lv2_3) and (axis_out_TREADY = ap_const_logic_0)))) and (icmp_ln118_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    axis_dst_data_V_1_ack_in <= axis_dst_data_V_1_state(1);
    axis_dst_data_V_1_ack_out <= axis_out_TREADY;

    axis_dst_data_V_1_data_out_assign_proc : process(axis_dst_data_V_1_payload_A, axis_dst_data_V_1_payload_B, axis_dst_data_V_1_sel)
    begin
        if ((axis_dst_data_V_1_sel = ap_const_logic_1)) then 
            axis_dst_data_V_1_data_out <= axis_dst_data_V_1_payload_B;
        else 
            axis_dst_data_V_1_data_out <= axis_dst_data_V_1_payload_A;
        end if; 
    end process;

    axis_dst_data_V_1_load_A <= (not(axis_dst_data_V_1_sel_wr) and axis_dst_data_V_1_state_cmp_full);
    axis_dst_data_V_1_load_B <= (axis_dst_data_V_1_state_cmp_full and axis_dst_data_V_1_sel_wr);
    axis_dst_data_V_1_sel <= axis_dst_data_V_1_sel_rd;
    axis_dst_data_V_1_state_cmp_full <= '0' when (axis_dst_data_V_1_state = ap_const_lv2_1) else '1';

    axis_dst_data_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln119_reg_172, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln119_reg_172 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            axis_dst_data_V_1_vld_in <= ap_const_logic_1;
        else 
            axis_dst_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    axis_dst_data_V_1_vld_out <= axis_dst_data_V_1_state(0);
    axis_dst_last_V_1_ack_in <= axis_dst_last_V_1_state(1);
    axis_dst_last_V_1_ack_out <= axis_out_TREADY;

    axis_dst_last_V_1_data_out_assign_proc : process(axis_dst_last_V_1_payload_A, axis_dst_last_V_1_payload_B, axis_dst_last_V_1_sel)
    begin
        if ((axis_dst_last_V_1_sel = ap_const_logic_1)) then 
            axis_dst_last_V_1_data_out <= axis_dst_last_V_1_payload_B;
        else 
            axis_dst_last_V_1_data_out <= axis_dst_last_V_1_payload_A;
        end if; 
    end process;

    axis_dst_last_V_1_load_A <= (not(axis_dst_last_V_1_sel_wr) and axis_dst_last_V_1_state_cmp_full);
    axis_dst_last_V_1_load_B <= (axis_dst_last_V_1_state_cmp_full and axis_dst_last_V_1_sel_wr);
    axis_dst_last_V_1_sel <= axis_dst_last_V_1_sel_rd;
    axis_dst_last_V_1_state_cmp_full <= '0' when (axis_dst_last_V_1_state = ap_const_lv2_1) else '1';

    axis_dst_last_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln119_reg_172, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln119_reg_172 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            axis_dst_last_V_1_vld_in <= ap_const_logic_1;
        else 
            axis_dst_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    axis_dst_last_V_1_vld_out <= axis_dst_last_V_1_state(0);
    axis_out_TDATA <= axis_dst_data_V_1_data_out;

    axis_out_TDATA_blk_n_assign_proc : process(axis_dst_data_V_1_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln119_reg_172, ap_enable_reg_pp0_iter2, icmp_ln119_reg_172_pp0_iter1_reg)
    begin
        if ((((icmp_ln119_reg_172_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((icmp_ln119_reg_172 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            axis_out_TDATA_blk_n <= axis_dst_data_V_1_state(1);
        else 
            axis_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    axis_out_TLAST <= axis_dst_last_V_1_data_out;
    axis_out_TVALID <= axis_dst_last_V_1_state(0);

    fifo7_blk_n_assign_proc : process(fifo7_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln119_reg_172)
    begin
        if (((icmp_ln119_reg_172 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            fifo7_blk_n <= fifo7_empty_n;
        else 
            fifo7_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fifo7_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln119_reg_172, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln119_reg_172 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fifo7_read <= ap_const_logic_1;
        else 
            fifo7_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln118_fu_106_p2 <= "1" when (yi_0_i_reg_84 = ap_const_lv11_438) else "0";
    icmp_ln119_fu_124_p2 <= "1" when (xi_0_i_reg_95 = ap_const_lv11_780) else "0";
    icmp_ln125_1_fu_136_p2 <= "1" when (xi_0_i_reg_95 = ap_const_lv11_77F) else "0";
    icmp_ln125_fu_118_p2 <= "1" when (yi_0_i_reg_84 = ap_const_lv11_437) else "0";
    or_ln_i_fu_147_p4 <= ((fifo7_dout & fifo7_dout) & fifo7_dout);
    xi_fu_130_p2 <= std_logic_vector(unsigned(xi_0_i_reg_95) + unsigned(ap_const_lv11_1));
    yi_fu_112_p2 <= std_logic_vector(unsigned(yi_0_i_reg_84) + unsigned(ap_const_lv11_1));
end behav;
